# Generated by Django 5.1.3 on 2024-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Kids', 'Kids'), ('Horror', 'Horror'), ('Sports', 'Sports'), ('Biography', 'Biography'), ('Tales', 'Tales')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Kids', 'Kids'), ('Horror', 'Horror'), ('Sports', 'Sports'), ('Biography', 'Biography'), ('Tales', 'Tales')], default='Fiction', max_length=100),
        ),
    ]
